// models/Student.js
// This file defines the Mongoose schema and model for student users.

const mongoose = require('mongoose'); // Import Mongoose

// Define the Student Schema
const studentSchema = new mongoose.Schema({
  // Unique ID for the student (can be generated by MongoDB or provided)
  id: {
    type: String, // Storing as String based on your JSON example
    unique: true,
    required: true,
    trim: true, // Remove whitespace from both ends of a string
  },
  // Student's roll number, required and unique for identification
  rollNumber: {
    type: String,
    required: true,
    unique: true,
    trim: true,
  },
  // Student's full name
  name: {
    type: String,
    required: true,
    trim: true,
  },
  // Student's email, required and unique for login
  email: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    lowercase: true, // Store emails in lowercase to ensure uniqueness across case
  },
  // Student's password (in a real app, this should be hashed, e.g., using bcrypt)
  password: {
    type: String,
    required: true,
  },
  // Student's department (e.g., "DS", "IT")
  department: {
    type: String,
    required: true,
    trim: true,
  },
  // Current academic year of the student
  year: {
    type: String, // Or Number, depending on how you want to represent it
    required: true,
    trim: true,
  },
  // Section (e.g., "A", "B")
  section: {
    type: String,
    required: true,
    trim: true,
  },
  // Semester (e.g., "3-1")
  semester: {
    type: String,
    required: true,
    trim: true,
  },
  // Student's phone number
  phone: {
    type: String,
    required: true,
    trim: true,
  },
  // Role of the user, should always be 'student' for this model
  role: {
    type: String,
    required: true,
    enum: ['student'], // Ensure only 'student' is allowed for this role
    default: 'student',
  },
}, {
  timestamps: true // Adds createdAt and updatedAt timestamps automatically
});

// Create the Mongoose Model from the Schema
const Student = mongoose.model('Student', studentSchema);

module.exports = Student; // Export the Student model
